# Generated by Django 3.2.3 on 2021-05-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('identity', models.CharField(max_length=30, verbose_name='아이디')),
                ('password', models.CharField(max_length=30, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('phone', models.IntegerField(verbose_name='전화번호')),
                ('register_data', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
            ],
        ),
    ]
